name: ValentCity
version: '2.14.1'
main: me.dantesys.valentCity.ValentCity
api-version: '1.21.3'
authors: [ Dantesys ]
description: Um plugin usando no servidor valent city
commands:
  reliquia:
    description: Recebe as reliquias
    usage: /<command> <player> <reliquiaName>
    permission: reliquias.use
    permission-message: Você não tem permissão
permissions:
  reliquias.use:
    description: Permiter pegar as reliquias
    default: op